AspNet_RazorWebPages/Pages/Modul04/PartialView1/PartialViewSample1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNet_RazorWebPages
{
    public class PartialViewSample1Model : PageModel
    {
        public void OnGet()
        {

        }
    }
}

AspNet_RazorWebPages/Pages/Modul04/PartialView1/PartialViewSample2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspNet_RazorWebPages
{
    public class PartialViewSample2Model : PageModel
    {
        public string[] Tage { get; set; } = new string[7];
        public void OnGet()
        {

        }

        public PartialViewResult OnGetExcel()
        {
            for (int i=0; i < 7; i++)
            {
                Tage[i] = Enum.GetName(typeof(DayOfWeek), i);
            }

            HttpContext.Response.ContentType = "application/vnd.ms-excel";

            return Partial("_Excel", this);
        }
    }
}

AspNet_RazorWebPages/Pages/Modul04/PartialView1/PartialViewSample1.cshtml
@page
@model AspNet_RazorWebPages.PartialViewSample1Model
@{
    ViewData["Title"] = "PartialViewSample1";
}

<h1>UsePartial Sample1</h1>

<partial name="_Zeit"/>

AspNet_RazorWebPages/Pages/Modul04/PartialView1/PartialViewSample2.cshtml
@page
@model AspNet_RazorWebPages.PartialViewSample2Model
@{
    ViewData["Title"] = "PartialViewSample2";
}

<h1>PartialViewSample2</h1>

<partial name="_Zeit" />
<a asp-page-handler="excel" class="btn btn-danger">Excel Export</a>

AspNet_RazorWebPages/Pages/Modul04/PartialView1/_Excel.cshtml
@model AspNet_RazorWebPages.PartialViewSample2Model

<table>
    <tr>
        <th>Wochentag</th>
    </tr>
    @foreach(var item in Model.Tage)
    {
        <tr>
            <td>@item</td>
        </tr>
    }
</table>

AspNet_RazorWebPages/Pages/Modul04/PartialView1/_Zeit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<i>@DateTime.Now</i>